
logging:
  level:
    cn:
      hunkier: DEBUG

    org:
      zalando:
        problem: DEBUG
      hibernate: DEBUG
      springframework:
        data: DEBUG
        jdbc: DEBUG
        security: DEBUG
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: test
    password: 123456
  jpa:
    generate-ddl: true